apiVersion: 1

datasources:
- name: InfluxDB-Covid19
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  password: secretpassword
  user: telegraf
  database: covid
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""